config/routes.rb
Rails.application.routes.draw do
  resources :datum, only: [:index, :new, :create, :destroy]
  resources :encrypted_file, only: [:index, :new, :create, :destroy]
  post '/datum/new', to: 'datum#create'
  post '/encrypted_file/new', to: 'encrypted_file#create'
  root 'welcome#welcome'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/datum.rb
class Datum < ApplicationRecord
  #attr_accessor :encryption, :key, :attachment
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  validates :name, presence: true
  validates :key, presence: true
  validates :encryption, presence: true
  validate :key_length_correct


  def key_length_correct
    case self.encryption
      when 'blowfish'
        return true if self.key.length>=4 and self.key.length<=56
        self.errors.add :key, 'Blowfish key must be between 4 and 56'
        return false
      when 'aes-256-cbc', 'aria-256-cbc'
        puts self
        return true if self.key.length == 32
        self.errors.add :key, "#{self.encryption} needs 32 letters long key"
        return false
      when 'cast5-cbc'
        return true if self.key.length ==16
        self.errors.add :key, 'CAST5 key must be 16 signs long'
        return false
      when 'des-ede3-cbc'
        return true if self.key.length == 21
        self.errors.add :key, '3DES key must be 21 signs long'
        return false
      else
        false
    end
  end
end
#aes-256-cbc aria-256-cbc blowfish cast5-cbc des-ede3-cbc

app/models/encrypted_file.rb
class EncryptedFile < ApplicationRecord
  #attr_accessor :encryption, :key, :attachment
  mount_uploader :attachment, EncryptedUploader# Tells rails to use this uploader for this model.
  validates :name, presence: true
  validates :key, presence: true
  validates :encryption, presence: true
  validate :key_length_correct

  def key_length_correct
    case self.encryption
      when 'blowfish'
        return true if self.key.length>=4 and self.key.length<=56
        self.errors.add :key, 'Blowfish key must be between 4 and 56'
      when 'aes-256-cbc', 'aria-256-cbc'
        return true if self.key.length == 32
        self.errors.add :key, "#{self.encryption} needs 32 letters long key"
      when 'cast5-cbc'
        return true if self.key.length ==16
        self.errors.add :key, 'CAST5 key must be 16 signs long'
      when 'des-ede3-cbc'
        return true if self.key.length == 21
        self.errors.add :key, '3DES key must be 21 signs long'
      else
        true
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/datum_controller.rb
class DatumController < ApplicationController
  def index
    @data = Datum.all
  end

  def new
    @data = Datum.new
  end

  def create
    @data = Datum.new(datum_params.except(:attachment))

    if @data.save
      @data.attachment = datum_params.delete :attachment
      redirect_to datum_index_url,
                  notice: "The file #{@data.name} has been uploaded." and return if @data.save
      render 'new'
    else
      render 'new'
    end
  end

  def destroy
    @data = Datum.find(params[:id])
    @data.destroy
    redirect_to datum_index_url, notice: "The file #{@data.name} has been deleted"
  end

  private

  def datum_params
    params.require(:data).permit(:name, :attachment, :key, :encryption)
  end
end

app/controllers/encrypted_file_controller.rb
class EncryptedFileController < ApplicationController
  def index
    @data = EncryptedFile.all
  end

  def new
    @data = EncryptedFile.new
  end

  def create
    @data = EncryptedFile.new(datum_params.except(:attachment))
    @data.attachment = datum_params.delete :attachment
    @data.valid?
    redirect_to encrypted_file_index_url,
                  notice: "The file #{@data.name} has been uploaded." and return if @data.save
    render 'new'
  end

  def destroy
    @data = EncryptedFile.find(params[:id])
    @data.destroy
    redirect_to encrypted_file_index_url, notice: "The file #{@data.name} has been deleted"
  end

  private

  def datum_params
    params.require(:data).permit(:name, :attachment, :key, :encryption)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def welcome

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datum_helper.rb
module DatumHelper
end

app/helpers/encrypted_file_helper.rb
module EncryptedFileHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/datum/create.html.erb
<h1>Datum#create</h1>
<p>Find me in app/views/datum/create.html.erb</p>

app/views/datum/destroy.html.erb
<h1>Datum#destroy</h1>
<p>Find me in app/views/datum/destroy.html.erb</p>

app/views/datum/index.html.erb
<% unless flash[:notice].blank? %>
    <div class = "alert alert-success">
      <%= flash[:notice] %>
    </div>
<% end %>

<br />

<%= link_to 'Upload file', new_datum_path, class: 'btn btn-primary' %>
<%= link_to 'Back', root_path, class: 'btn btn-primary' %>
<br />
<br />

<table class = "table table-bordered table-striped">
  <thead>.
  <tr>
    <th>Name</th>
    <th>Encryption</th>
    <th>Key</th>
    <th>Key in Hex</th>
    <th>Download Link</th>
    <th> </th>
  </tr>
  </thead>

  <tbody>
  <% @data.each do |file| %>

      <tr>
        <td><%= file.name %></td>
        <td><%= file.encryption%></td>
        <td><%= file.key%></td>
        <td><%= file.key.unpack('H*')%></td>
        <td><%= link_to 'Download file', file.attachment_url %></td>
        <td><%= button_to 'Delete',  file, method: :delete, class: 'btn btn-danger',
                          confirm: "Are you sure that you wish to delete #{file.name}?" %></td>
      </tr>

  <% end %>
  </tbody>

</table>

app/views/datum/new.html.erb
<% unless @data.errors.empty? %>
    <div class = "alert alert-error">

      <ul>
        <% @data.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>

    </div>
<% end %>

<div class = "well">
  <%= form_for :data, html: { multipart: true } do |f| %>
      <div class = 'form-group'>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class = 'form-group'>
        <%= f.label :attachment %>
        <%= f.file_field :attachment, class: 'form-control-file' %>
      </div>
      <div class = 'form-group'>
        <%= f.label :key %>
        <%= f.text_field :key, class: 'form-control' %>
      </div>
      <div class = 'form-group'>
        <%= f.label :encryption %>
        <br/>
        <%= f.select :encryption, %w(aes-256-cbc aria-256-cbc blowfish cast5-cbc des-ede3-cbc), class: 'form-control' %>
      </div>
      <%= f.submit 'Decrypt', class: 'btn btn-primary'%>
      <%= link_to 'Back', datum_index_url, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/encrypted_file/create.html.erb
<h1>EncryptedFile#create</h1>
<p>Find me in app/views/encrypted_file/create.html.erb</p>

app/views/encrypted_file/destroy.html.erb
<h1>EncryptedFile#destroy</h1>
<p>Find me in app/views/encrypted_file/destroy.html.erb</p>

app/views/encrypted_file/index.html.erb
<% unless flash[:notice].blank? %>
    <div class = "alert alert-success">
      <%= flash[:notice] %>
    </div>
<% end %>

<br />

<%= link_to 'Upload file', new_encrypted_file_path, class: 'btn btn-primary' %>
<%= link_to 'Back', root_path, class: 'btn btn-primary' %>
<br />
<br />

<table class = "table table-bordered table-striped">
  <thead>.
  <tr>
    <th>Name</th>
    <th>Encryption</th>
    <th>Key</th>
    <th>Key in Hex</th>
    <th>Download Link</th>
    <th> </th>
  </tr>
  </thead>

  <tbody>
  <% @data.each do |file| %>

      <tr>
        <td><%= file.name %></td>
        <td><%= file.encryption%></td>
        <td><%= file.key%></td>
        <td><%= file.key.unpack('H*') unless file.key.nil?%></td>
        <td><%= link_to 'Download file', file.attachment_url %></td>
        <td><%= button_to 'Delete',  file, method: :delete, class: 'btn btn-danger',
                          confirm: "Are you sure that you wish to delete #{file.name}?" %></td>
      </tr>

  <% end %>
  </tbody>

</table>

app/views/encrypted_file/new.html.erb
<% unless @data.errors.empty? %>
    <div class = "alert alert-error">

      <ul>
        <% @data.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>

    </div>
<% end %>


<div class = "well">
  <%= form_for :data, html: { multipart: true } do |f| %>
      <div class = 'form-group'>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class = 'form-group'>
      <%= f.label :attachment %>
      <%= f.file_field :attachment, class: 'form-control-file' %>
      </div>
      <div class = 'form-group'>
      <%= f.label :key %>
      <%= f.text_field :key, class: 'form-control' %>
      </div>
      <div class = 'form-group'>
      <%= f.label :encryption %>
        <br/>
      <%= f.select :encryption, %w(aes-256-cbc aria-256-cbc blowfish cast5-cbc des-ede3-cbc), class: 'form-control' %>
      </div>
      <%= f.submit 'Decrypt', class: 'btn btn-primary'%>
      <%= link_to 'Back', encrypted_file_index_url, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oibi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class = "container" style = "padding-top:20px;">
    <%= yield %>
  </div>
  </body>
</html>

app/views/welcome/welcome.html.erb
<h1>OiBI project main page</h1>
<%= link_to 'Encrypt files', datum_index_url, class: 'btn btn-primary' %>
<%= link_to 'Decrypt files', encrypted_file_index_url, class: 'btn btn-primary' %>